2021-05-02 13:51:13 TRACE Driver:25 - Preinitializing TRMS
2021-05-02 14:04:48 TRACE Driver:25 - Preinitializing TRMS
2021-05-02 15:48:27 TRACE Driver:25 - Preinitializing TRMS
2021-05-02 15:48:27 TRACE AdminDaoCassImpl:28 - Obtaining Cassandra session
2021-05-02 15:48:32 TRACE AdminDaoCassImpl:33 - Cassandra session not obtained: 
java.lang.IllegalArgumentException: Error instantiating class DefaultSslEngineFactory (specified by advanced.ssl-engine-factory.class): Cannot initialize SSL Context
	at com.datastax.oss.driver.internal.core.util.Reflection.buildFromConfig(Reflection.java:253) ~[java-driver-core-4.11.0.jar:?]
	at com.datastax.oss.driver.internal.core.util.Reflection.buildFromConfig(Reflection.java:108) ~[java-driver-core-4.11.0.jar:?]
	at com.datastax.oss.driver.internal.core.context.DefaultDriverContext.buildSslEngineFactory(DefaultDriverContext.java:409) ~[java-driver-core-4.11.0.jar:?]
	at com.datastax.oss.driver.internal.core.context.DefaultDriverContext.lambda$new$4(DefaultDriverContext.java:277) ~[java-driver-core-4.11.0.jar:?]
	at com.datastax.oss.driver.internal.core.util.concurrent.LazyReference.get(LazyReference.java:55) ~[java-driver-core-4.11.0.jar:?]
	at com.datastax.oss.driver.internal.core.context.DefaultDriverContext.getSslEngineFactory(DefaultDriverContext.java:727) ~[java-driver-core-4.11.0.jar:?]
	at com.datastax.oss.driver.internal.core.context.DefaultDriverContext.buildSslHandlerFactory(DefaultDriverContext.java:464) ~[java-driver-core-4.11.0.jar:?]
	at com.datastax.oss.driver.internal.core.util.concurrent.LazyReference.get(LazyReference.java:55) ~[java-driver-core-4.11.0.jar:?]
	at com.datastax.oss.driver.internal.core.context.DefaultDriverContext.getSslHandlerFactory(DefaultDriverContext.java:793) ~[java-driver-core-4.11.0.jar:?]
	at com.datastax.oss.driver.internal.core.session.DefaultSession$SingleThreaded.init(DefaultSession.java:348) ~[java-driver-core-4.11.0.jar:?]
	at com.datastax.oss.driver.internal.core.session.DefaultSession$SingleThreaded.access$1100(DefaultSession.java:300) ~[java-driver-core-4.11.0.jar:?]
	at com.datastax.oss.driver.internal.core.session.DefaultSession.lambda$init$0(DefaultSession.java:146) ~[java-driver-core-4.11.0.jar:?]
	at io.netty.util.concurrent.PromiseTask.runTask(PromiseTask.java:98) ~[netty-common-4.1.60.Final.jar:4.1.60.Final]
	at io.netty.util.concurrent.PromiseTask.run(PromiseTask.java:106) ~[netty-common-4.1.60.Final.jar:4.1.60.Final]
	at io.netty.channel.DefaultEventLoop.run(DefaultEventLoop.java:54) ~[netty-transport-4.1.60.Final.jar:4.1.60.Final]
	at io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:989) ~[netty-common-4.1.60.Final.jar:4.1.60.Final]
	at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74) ~[netty-common-4.1.60.Final.jar:4.1.60.Final]
	at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30) ~[netty-common-4.1.60.Final.jar:4.1.60.Final]
	at java.lang.Thread.run(Unknown Source) ~[?:1.8.0_281]
Caused by: java.lang.IllegalStateException: Cannot initialize SSL Context
	at com.datastax.oss.driver.internal.core.ssl.DefaultSslEngineFactory.<init>(DefaultSslEngineFactory.java:74) ~[java-driver-core-4.11.0.jar:?]
	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method) ~[?:1.8.0_281]
	at sun.reflect.NativeConstructorAccessorImpl.newInstance(Unknown Source) ~[?:1.8.0_281]
	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(Unknown Source) ~[?:1.8.0_281]
	at java.lang.reflect.Constructor.newInstance(Unknown Source) ~[?:1.8.0_281]
	at com.datastax.oss.driver.internal.core.util.Reflection.buildFromConfig(Reflection.java:246) ~[java-driver-core-4.11.0.jar:?]
	... 18 more
Caused by: java.io.IOException: keystore password was incorrect
	at sun.security.pkcs12.PKCS12KeyStore.engineLoad(Unknown Source) ~[?:1.8.0_281]
	at sun.security.provider.KeyStoreDelegator.engineLoad(Unknown Source) ~[?:1.8.0_281]
	at sun.security.provider.JavaKeyStore$DualFormatJKS.engineLoad(Unknown Source) ~[?:1.8.0_281]
	at java.security.KeyStore.load(Unknown Source) ~[?:1.8.0_281]
	at com.datastax.oss.driver.internal.core.ssl.DefaultSslEngineFactory.buildContext(DefaultSslEngineFactory.java:126) ~[java-driver-core-4.11.0.jar:?]
	at com.datastax.oss.driver.internal.core.ssl.DefaultSslEngineFactory.<init>(DefaultSslEngineFactory.java:72) ~[java-driver-core-4.11.0.jar:?]
	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method) ~[?:1.8.0_281]
	at sun.reflect.NativeConstructorAccessorImpl.newInstance(Unknown Source) ~[?:1.8.0_281]
	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(Unknown Source) ~[?:1.8.0_281]
	at java.lang.reflect.Constructor.newInstance(Unknown Source) ~[?:1.8.0_281]
	at com.datastax.oss.driver.internal.core.util.Reflection.buildFromConfig(Reflection.java:246) ~[java-driver-core-4.11.0.jar:?]
	... 18 more
Caused by: java.security.UnrecoverableKeyException: failed to decrypt safe contents entry: javax.crypto.BadPaddingException: Given final block not properly padded. Such issues can arise if a bad key is used during decryption.
	at sun.security.pkcs12.PKCS12KeyStore.engineLoad(Unknown Source) ~[?:1.8.0_281]
	at sun.security.provider.KeyStoreDelegator.engineLoad(Unknown Source) ~[?:1.8.0_281]
	at sun.security.provider.JavaKeyStore$DualFormatJKS.engineLoad(Unknown Source) ~[?:1.8.0_281]
	at java.security.KeyStore.load(Unknown Source) ~[?:1.8.0_281]
	at com.datastax.oss.driver.internal.core.ssl.DefaultSslEngineFactory.buildContext(DefaultSslEngineFactory.java:126) ~[java-driver-core-4.11.0.jar:?]
	at com.datastax.oss.driver.internal.core.ssl.DefaultSslEngineFactory.<init>(DefaultSslEngineFactory.java:72) ~[java-driver-core-4.11.0.jar:?]
	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method) ~[?:1.8.0_281]
	at sun.reflect.NativeConstructorAccessorImpl.newInstance(Unknown Source) ~[?:1.8.0_281]
	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(Unknown Source) ~[?:1.8.0_281]
	at java.lang.reflect.Constructor.newInstance(Unknown Source) ~[?:1.8.0_281]
	at com.datastax.oss.driver.internal.core.util.Reflection.buildFromConfig(Reflection.java:246) ~[java-driver-core-4.11.0.jar:?]
	... 18 more
2021-05-02 15:48:32 TRACE AdminServiceImpl:17 - Admin Dao instantiated
2021-05-02 15:48:32 TRACE AdminServiceImpl:18 - Admin svc instantiated
2021-05-02 15:48:32 TRACE DriverServiceImpl:16 - new Admin svc instantiated
2021-05-02 15:48:32 TRACE AdminServiceImpl:67 - Verifying existence of Admins in DB
2021-05-02 15:48:32 TRACE AdminDaoCassImpl:43 - Empty list of Admins instantiated:

2021-05-02 15:48:32 TRACE AdminDaoCassImpl:46 - Select Admin-list query assigned:

2021-05-02 17:24:25 TRACE Driver:25 - Preinitializing TRMS
2021-05-02 17:24:25 TRACE AdminDaoCassImpl:28 - Obtaining Cassandra session
2021-05-02 17:24:30 TRACE AdminDaoCassImpl:33 - Cassandra session not obtained: 
java.lang.IllegalArgumentException: Error instantiating class DefaultSslEngineFactory (specified by advanced.ssl-engine-factory.class): Cannot initialize SSL Context
	at com.datastax.oss.driver.internal.core.util.Reflection.buildFromConfig(Reflection.java:253) ~[java-driver-core-4.11.0.jar:?]
	at com.datastax.oss.driver.internal.core.util.Reflection.buildFromConfig(Reflection.java:108) ~[java-driver-core-4.11.0.jar:?]
	at com.datastax.oss.driver.internal.core.context.DefaultDriverContext.buildSslEngineFactory(DefaultDriverContext.java:409) ~[java-driver-core-4.11.0.jar:?]
	at com.datastax.oss.driver.internal.core.context.DefaultDriverContext.lambda$new$4(DefaultDriverContext.java:277) ~[java-driver-core-4.11.0.jar:?]
	at com.datastax.oss.driver.internal.core.util.concurrent.LazyReference.get(LazyReference.java:55) ~[java-driver-core-4.11.0.jar:?]
	at com.datastax.oss.driver.internal.core.context.DefaultDriverContext.getSslEngineFactory(DefaultDriverContext.java:727) ~[java-driver-core-4.11.0.jar:?]
	at com.datastax.oss.driver.internal.core.context.DefaultDriverContext.buildSslHandlerFactory(DefaultDriverContext.java:464) ~[java-driver-core-4.11.0.jar:?]
	at com.datastax.oss.driver.internal.core.util.concurrent.LazyReference.get(LazyReference.java:55) ~[java-driver-core-4.11.0.jar:?]
	at com.datastax.oss.driver.internal.core.context.DefaultDriverContext.getSslHandlerFactory(DefaultDriverContext.java:793) ~[java-driver-core-4.11.0.jar:?]
	at com.datastax.oss.driver.internal.core.session.DefaultSession$SingleThreaded.init(DefaultSession.java:348) ~[java-driver-core-4.11.0.jar:?]
	at com.datastax.oss.driver.internal.core.session.DefaultSession$SingleThreaded.access$1100(DefaultSession.java:300) ~[java-driver-core-4.11.0.jar:?]
	at com.datastax.oss.driver.internal.core.session.DefaultSession.lambda$init$0(DefaultSession.java:146) ~[java-driver-core-4.11.0.jar:?]
	at io.netty.util.concurrent.PromiseTask.runTask(PromiseTask.java:98) ~[netty-common-4.1.60.Final.jar:4.1.60.Final]
	at io.netty.util.concurrent.PromiseTask.run(PromiseTask.java:106) ~[netty-common-4.1.60.Final.jar:4.1.60.Final]
	at io.netty.channel.DefaultEventLoop.run(DefaultEventLoop.java:54) ~[netty-transport-4.1.60.Final.jar:4.1.60.Final]
	at io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:989) ~[netty-common-4.1.60.Final.jar:4.1.60.Final]
	at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74) ~[netty-common-4.1.60.Final.jar:4.1.60.Final]
	at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30) ~[netty-common-4.1.60.Final.jar:4.1.60.Final]
	at java.lang.Thread.run(Unknown Source) ~[?:1.8.0_281]
Caused by: java.lang.IllegalStateException: Cannot initialize SSL Context
	at com.datastax.oss.driver.internal.core.ssl.DefaultSslEngineFactory.<init>(DefaultSslEngineFactory.java:74) ~[java-driver-core-4.11.0.jar:?]
	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method) ~[?:1.8.0_281]
	at sun.reflect.NativeConstructorAccessorImpl.newInstance(Unknown Source) ~[?:1.8.0_281]
	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(Unknown Source) ~[?:1.8.0_281]
	at java.lang.reflect.Constructor.newInstance(Unknown Source) ~[?:1.8.0_281]
	at com.datastax.oss.driver.internal.core.util.Reflection.buildFromConfig(Reflection.java:246) ~[java-driver-core-4.11.0.jar:?]
	... 18 more
Caused by: java.io.IOException: keystore password was incorrect
	at sun.security.pkcs12.PKCS12KeyStore.engineLoad(Unknown Source) ~[?:1.8.0_281]
	at sun.security.provider.KeyStoreDelegator.engineLoad(Unknown Source) ~[?:1.8.0_281]
	at sun.security.provider.JavaKeyStore$DualFormatJKS.engineLoad(Unknown Source) ~[?:1.8.0_281]
	at java.security.KeyStore.load(Unknown Source) ~[?:1.8.0_281]
	at com.datastax.oss.driver.internal.core.ssl.DefaultSslEngineFactory.buildContext(DefaultSslEngineFactory.java:126) ~[java-driver-core-4.11.0.jar:?]
	at com.datastax.oss.driver.internal.core.ssl.DefaultSslEngineFactory.<init>(DefaultSslEngineFactory.java:72) ~[java-driver-core-4.11.0.jar:?]
	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method) ~[?:1.8.0_281]
	at sun.reflect.NativeConstructorAccessorImpl.newInstance(Unknown Source) ~[?:1.8.0_281]
	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(Unknown Source) ~[?:1.8.0_281]
	at java.lang.reflect.Constructor.newInstance(Unknown Source) ~[?:1.8.0_281]
	at com.datastax.oss.driver.internal.core.util.Reflection.buildFromConfig(Reflection.java:246) ~[java-driver-core-4.11.0.jar:?]
	... 18 more
Caused by: java.security.UnrecoverableKeyException: failed to decrypt safe contents entry: javax.crypto.BadPaddingException: Given final block not properly padded. Such issues can arise if a bad key is used during decryption.
	at sun.security.pkcs12.PKCS12KeyStore.engineLoad(Unknown Source) ~[?:1.8.0_281]
	at sun.security.provider.KeyStoreDelegator.engineLoad(Unknown Source) ~[?:1.8.0_281]
	at sun.security.provider.JavaKeyStore$DualFormatJKS.engineLoad(Unknown Source) ~[?:1.8.0_281]
	at java.security.KeyStore.load(Unknown Source) ~[?:1.8.0_281]
	at com.datastax.oss.driver.internal.core.ssl.DefaultSslEngineFactory.buildContext(DefaultSslEngineFactory.java:126) ~[java-driver-core-4.11.0.jar:?]
	at com.datastax.oss.driver.internal.core.ssl.DefaultSslEngineFactory.<init>(DefaultSslEngineFactory.java:72) ~[java-driver-core-4.11.0.jar:?]
	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method) ~[?:1.8.0_281]
	at sun.reflect.NativeConstructorAccessorImpl.newInstance(Unknown Source) ~[?:1.8.0_281]
	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(Unknown Source) ~[?:1.8.0_281]
	at java.lang.reflect.Constructor.newInstance(Unknown Source) ~[?:1.8.0_281]
	at com.datastax.oss.driver.internal.core.util.Reflection.buildFromConfig(Reflection.java:246) ~[java-driver-core-4.11.0.jar:?]
	... 18 more
2021-05-02 17:24:30 TRACE AdminServiceImpl:17 - Admin Dao instantiated
2021-05-02 17:24:30 TRACE AdminServiceImpl:18 - Admin svc instantiated
2021-05-02 17:24:30 TRACE DriverServiceImpl:16 - new Admin svc instantiated
2021-05-02 17:24:30 TRACE AdminServiceImpl:67 - Verifying existence of Admins in DB
2021-05-02 17:24:30 TRACE AdminDaoCassImpl:43 - Empty list of Admins instantiated:

2021-05-02 17:24:30 TRACE AdminDaoCassImpl:46 - Select Admin-list query assigned:

2021-05-02 17:36:09 TRACE CassandraUtil:16 - Establishing connection with Cassandra
2021-05-02 17:36:13 ERROR CassandraUtil:21 - Method threw exception: java.lang.IllegalArgumentException: Error instantiating class DefaultSslEngineFactory (specified by advanced.ssl-engine-factory.class): Cannot initialize SSL Context
2021-05-02 17:36:13 WARN  CassandraUtil:23 - com.datastax.oss.driver.internal.core.util.Reflection.buildFromConfig(Reflection.java:253)
2021-05-02 17:36:13 WARN  CassandraUtil:23 - com.datastax.oss.driver.internal.core.util.Reflection.buildFromConfig(Reflection.java:108)
2021-05-02 17:36:13 WARN  CassandraUtil:23 - com.datastax.oss.driver.internal.core.context.DefaultDriverContext.buildSslEngineFactory(DefaultDriverContext.java:409)
2021-05-02 17:36:13 WARN  CassandraUtil:23 - com.datastax.oss.driver.internal.core.context.DefaultDriverContext.lambda$new$4(DefaultDriverContext.java:277)
2021-05-02 17:36:13 WARN  CassandraUtil:23 - com.datastax.oss.driver.internal.core.util.concurrent.LazyReference.get(LazyReference.java:55)
2021-05-02 17:36:13 WARN  CassandraUtil:23 - com.datastax.oss.driver.internal.core.context.DefaultDriverContext.getSslEngineFactory(DefaultDriverContext.java:727)
2021-05-02 17:36:13 WARN  CassandraUtil:23 - com.datastax.oss.driver.internal.core.context.DefaultDriverContext.buildSslHandlerFactory(DefaultDriverContext.java:464)
2021-05-02 17:36:13 WARN  CassandraUtil:23 - com.datastax.oss.driver.internal.core.util.concurrent.LazyReference.get(LazyReference.java:55)
2021-05-02 17:36:13 WARN  CassandraUtil:23 - com.datastax.oss.driver.internal.core.context.DefaultDriverContext.getSslHandlerFactory(DefaultDriverContext.java:793)
2021-05-02 17:36:13 WARN  CassandraUtil:23 - com.datastax.oss.driver.internal.core.session.DefaultSession$SingleThreaded.init(DefaultSession.java:348)
2021-05-02 17:36:13 WARN  CassandraUtil:23 - com.datastax.oss.driver.internal.core.session.DefaultSession$SingleThreaded.access$1100(DefaultSession.java:300)
2021-05-02 17:36:13 WARN  CassandraUtil:23 - com.datastax.oss.driver.internal.core.session.DefaultSession.lambda$init$0(DefaultSession.java:146)
2021-05-02 17:36:13 WARN  CassandraUtil:23 - io.netty.util.concurrent.PromiseTask.runTask(PromiseTask.java:98)
2021-05-02 17:36:13 WARN  CassandraUtil:23 - io.netty.util.concurrent.PromiseTask.run(PromiseTask.java:106)
2021-05-02 17:36:13 WARN  CassandraUtil:23 - io.netty.channel.DefaultEventLoop.run(DefaultEventLoop.java:54)
2021-05-02 17:36:13 WARN  CassandraUtil:23 - io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:989)
2021-05-02 17:36:13 WARN  CassandraUtil:23 - io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74)
2021-05-02 17:36:13 WARN  CassandraUtil:23 - io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
2021-05-02 17:36:13 WARN  CassandraUtil:23 - java.lang.Thread.run(Unknown Source)
2021-05-02 17:41:14 TRACE Driver:36 - hi curls
2021-05-02 17:41:32 TRACE CassandraUtil:16 - Establishing connection with Cassandra
2021-05-02 17:41:37 ERROR CassandraUtil:21 - Method threw exception: java.lang.IllegalArgumentException: Error instantiating class DefaultSslEngineFactory (specified by advanced.ssl-engine-factory.class): Cannot initialize SSL Context
2021-05-02 17:41:37 WARN  CassandraUtil:23 - com.datastax.oss.driver.internal.core.util.Reflection.buildFromConfig(Reflection.java:253)
2021-05-02 17:41:37 WARN  CassandraUtil:23 - com.datastax.oss.driver.internal.core.util.Reflection.buildFromConfig(Reflection.java:108)
2021-05-02 17:41:37 WARN  CassandraUtil:23 - com.datastax.oss.driver.internal.core.context.DefaultDriverContext.buildSslEngineFactory(DefaultDriverContext.java:409)
2021-05-02 17:41:37 WARN  CassandraUtil:23 - com.datastax.oss.driver.internal.core.context.DefaultDriverContext.lambda$new$4(DefaultDriverContext.java:277)
2021-05-02 17:41:37 WARN  CassandraUtil:23 - com.datastax.oss.driver.internal.core.util.concurrent.LazyReference.get(LazyReference.java:55)
2021-05-02 17:41:37 WARN  CassandraUtil:23 - com.datastax.oss.driver.internal.core.context.DefaultDriverContext.getSslEngineFactory(DefaultDriverContext.java:727)
2021-05-02 17:41:37 WARN  CassandraUtil:23 - com.datastax.oss.driver.internal.core.context.DefaultDriverContext.buildSslHandlerFactory(DefaultDriverContext.java:464)
2021-05-02 17:41:37 WARN  CassandraUtil:23 - com.datastax.oss.driver.internal.core.util.concurrent.LazyReference.get(LazyReference.java:55)
2021-05-02 17:41:37 WARN  CassandraUtil:23 - com.datastax.oss.driver.internal.core.context.DefaultDriverContext.getSslHandlerFactory(DefaultDriverContext.java:793)
2021-05-02 17:41:37 WARN  CassandraUtil:23 - com.datastax.oss.driver.internal.core.session.DefaultSession$SingleThreaded.init(DefaultSession.java:348)
2021-05-02 17:41:37 WARN  CassandraUtil:23 - com.datastax.oss.driver.internal.core.session.DefaultSession$SingleThreaded.access$1100(DefaultSession.java:300)
2021-05-02 17:41:37 WARN  CassandraUtil:23 - com.datastax.oss.driver.internal.core.session.DefaultSession.lambda$init$0(DefaultSession.java:146)
2021-05-02 17:41:37 WARN  CassandraUtil:23 - io.netty.util.concurrent.PromiseTask.runTask(PromiseTask.java:98)
2021-05-02 17:41:37 WARN  CassandraUtil:23 - io.netty.util.concurrent.PromiseTask.run(PromiseTask.java:106)
2021-05-02 17:41:37 WARN  CassandraUtil:23 - io.netty.channel.DefaultEventLoop.run(DefaultEventLoop.java:54)
2021-05-02 17:41:37 WARN  CassandraUtil:23 - io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:989)
2021-05-02 17:41:37 WARN  CassandraUtil:23 - io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74)
2021-05-02 17:41:37 WARN  CassandraUtil:23 - io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
2021-05-02 17:41:37 WARN  CassandraUtil:23 - java.lang.Thread.run(Unknown Source)
2021-05-02 17:47:35 TRACE CassandraUtil:16 - Establishing connection with Cassandra
2021-05-02 17:47:41 ERROR CassandraUtil:21 - Method threw exception: java.lang.IllegalArgumentException: Error instantiating class DefaultSslEngineFactory (specified by advanced.ssl-engine-factory.class): Cannot initialize SSL Context
2021-05-02 17:47:41 WARN  CassandraUtil:23 - com.datastax.oss.driver.internal.core.util.Reflection.buildFromConfig(Reflection.java:253)
2021-05-02 17:47:41 WARN  CassandraUtil:23 - com.datastax.oss.driver.internal.core.util.Reflection.buildFromConfig(Reflection.java:108)
2021-05-02 17:47:41 WARN  CassandraUtil:23 - com.datastax.oss.driver.internal.core.context.DefaultDriverContext.buildSslEngineFactory(DefaultDriverContext.java:409)
2021-05-02 17:47:41 WARN  CassandraUtil:23 - com.datastax.oss.driver.internal.core.context.DefaultDriverContext.lambda$new$4(DefaultDriverContext.java:277)
2021-05-02 17:47:41 WARN  CassandraUtil:23 - com.datastax.oss.driver.internal.core.util.concurrent.LazyReference.get(LazyReference.java:55)
2021-05-02 17:47:41 WARN  CassandraUtil:23 - com.datastax.oss.driver.internal.core.context.DefaultDriverContext.getSslEngineFactory(DefaultDriverContext.java:727)
2021-05-02 17:47:41 WARN  CassandraUtil:23 - com.datastax.oss.driver.internal.core.context.DefaultDriverContext.buildSslHandlerFactory(DefaultDriverContext.java:464)
2021-05-02 17:47:41 WARN  CassandraUtil:23 - com.datastax.oss.driver.internal.core.util.concurrent.LazyReference.get(LazyReference.java:55)
2021-05-02 17:47:41 WARN  CassandraUtil:23 - com.datastax.oss.driver.internal.core.context.DefaultDriverContext.getSslHandlerFactory(DefaultDriverContext.java:793)
2021-05-02 17:47:41 WARN  CassandraUtil:23 - com.datastax.oss.driver.internal.core.session.DefaultSession$SingleThreaded.init(DefaultSession.java:348)
2021-05-02 17:47:41 WARN  CassandraUtil:23 - com.datastax.oss.driver.internal.core.session.DefaultSession$SingleThreaded.access$1100(DefaultSession.java:300)
2021-05-02 17:47:41 WARN  CassandraUtil:23 - com.datastax.oss.driver.internal.core.session.DefaultSession.lambda$init$0(DefaultSession.java:146)
2021-05-02 17:47:41 WARN  CassandraUtil:23 - io.netty.util.concurrent.PromiseTask.runTask(PromiseTask.java:98)
2021-05-02 17:47:41 WARN  CassandraUtil:23 - io.netty.util.concurrent.PromiseTask.run(PromiseTask.java:106)
2021-05-02 17:47:41 WARN  CassandraUtil:23 - io.netty.channel.DefaultEventLoop.run(DefaultEventLoop.java:54)
2021-05-02 17:47:41 WARN  CassandraUtil:23 - io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:989)
2021-05-02 17:47:41 WARN  CassandraUtil:23 - io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74)
2021-05-02 17:47:41 WARN  CassandraUtil:23 - io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
2021-05-02 17:47:41 WARN  CassandraUtil:23 - java.lang.Thread.run(Unknown Source)
2021-05-02 17:50:01 TRACE CassandraUtil:16 - Establishing connection with Cassandra
2021-05-02 17:50:07 ERROR CassandraUtil:21 - Method threw exception: java.lang.IllegalArgumentException: Error instantiating class DefaultSslEngineFactory (specified by advanced.ssl-engine-factory.class): Cannot initialize SSL Context
2021-05-02 17:50:07 WARN  CassandraUtil:23 - com.datastax.oss.driver.internal.core.util.Reflection.buildFromConfig(Reflection.java:253)
2021-05-02 17:50:07 WARN  CassandraUtil:23 - com.datastax.oss.driver.internal.core.util.Reflection.buildFromConfig(Reflection.java:108)
2021-05-02 17:50:07 WARN  CassandraUtil:23 - com.datastax.oss.driver.internal.core.context.DefaultDriverContext.buildSslEngineFactory(DefaultDriverContext.java:409)
2021-05-02 17:50:07 WARN  CassandraUtil:23 - com.datastax.oss.driver.internal.core.context.DefaultDriverContext.lambda$new$4(DefaultDriverContext.java:277)
2021-05-02 17:50:07 WARN  CassandraUtil:23 - com.datastax.oss.driver.internal.core.util.concurrent.LazyReference.get(LazyReference.java:55)
2021-05-02 17:50:07 WARN  CassandraUtil:23 - com.datastax.oss.driver.internal.core.context.DefaultDriverContext.getSslEngineFactory(DefaultDriverContext.java:727)
2021-05-02 17:50:07 WARN  CassandraUtil:23 - com.datastax.oss.driver.internal.core.context.DefaultDriverContext.buildSslHandlerFactory(DefaultDriverContext.java:464)
2021-05-02 17:50:07 WARN  CassandraUtil:23 - com.datastax.oss.driver.internal.core.util.concurrent.LazyReference.get(LazyReference.java:55)
2021-05-02 17:50:07 WARN  CassandraUtil:23 - com.datastax.oss.driver.internal.core.context.DefaultDriverContext.getSslHandlerFactory(DefaultDriverContext.java:793)
2021-05-02 17:50:07 WARN  CassandraUtil:23 - com.datastax.oss.driver.internal.core.session.DefaultSession$SingleThreaded.init(DefaultSession.java:348)
2021-05-02 17:50:07 WARN  CassandraUtil:23 - com.datastax.oss.driver.internal.core.session.DefaultSession$SingleThreaded.access$1100(DefaultSession.java:300)
2021-05-02 17:50:07 WARN  CassandraUtil:23 - com.datastax.oss.driver.internal.core.session.DefaultSession.lambda$init$0(DefaultSession.java:146)
2021-05-02 17:50:07 WARN  CassandraUtil:23 - io.netty.util.concurrent.PromiseTask.runTask(PromiseTask.java:98)
2021-05-02 17:50:07 WARN  CassandraUtil:23 - io.netty.util.concurrent.PromiseTask.run(PromiseTask.java:106)
2021-05-02 17:50:07 WARN  CassandraUtil:23 - io.netty.channel.DefaultEventLoop.run(DefaultEventLoop.java:54)
2021-05-02 17:50:07 WARN  CassandraUtil:23 - io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:989)
2021-05-02 17:50:07 WARN  CassandraUtil:23 - io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74)
2021-05-02 17:50:07 WARN  CassandraUtil:23 - io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
2021-05-02 17:50:07 WARN  CassandraUtil:23 - java.lang.Thread.run(Unknown Source)
